services:
  mysql:
    image: mysql:8.0.20
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      interval: 10s
      retries: 10
